# Base image
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y curl cron nano && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY execute.sh /app/execute.sh
COPY test /app/test

 RUN echo '* * * * * root /app/execute.sh >> /var/log/output.log 2>&1' > /etc/cron.d/execute-tests-job \
    && touch /var/log/output.log \
    && chmod 0644 /etc/cron.d/execute-tests-job \
    && chmod +x /app/execute.sh

CMD cron && tail -f /var/log/output.log